services:
  postgres:
    build:
      target: with-pgtap
      additional_contexts:
        pg_climb: https://github.com/lgrosz/pg_climb.git
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

