name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGDATABASE: climb-pg_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup test containers
        run: docker compose up -d

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pgtap sqitch

      - name: Load pgTAP
        run: psql -d climb-pg_test -c "CREATE EXTENSION pgtap;"

      - name: Deploy database schema using Sqitch
        run: sqitch deploy

      - name: Run tests with pg_prove
        run: pg_prove -d climb-pg_test

